name: OpenaiGPTLLM
model_id: gpt-3.5-turbo
api_key: ${env| custom_openai_key, openai_api_key}
endpoint: ${env| custom_openai_endpoint, https://api.openai.com/v1}
temperature: 0
stream: false
response_format: text
use_default_sys_prompt: false