- name: COTReasoning
  llm: ${sub|text_res}
  #tool_manager: ${sub|all_tools}
  output_parser:
    name: StrParser


- name: COTExtract
  llm: ${sub|text_res}
  #tool_manager: ${sub|all_tools}
  output_parser:
    name: StrParser

- name: COTConclusion
  llm: ${sub|text_res}
  #tool_manager: ${sub|all_tools}
  output_parser:
    name: StrParser