from omagent_core.models.llms.base import BaseLLMBackend
from omagent_core.utils.registry import registry
from omagent_core.utils.general import read_image
from omagent_core.models.llms.openai_gpt import OpenaiGPTLLM
from omagent_core.engine.worker.base import BaseWorker
from omagent_core.advanced_components.workflow.ZoomEye.schemas.tree import ImageTree
from omagent_core.advanced_components.workflow.ZoomEye.schemas.utils import *

@registry.register_worker()
class VisualCueGeneration(BaseWorker, BaseLLMBackend):
    """
    A worker class that generates visual cues from an image using a language model.
    Visual cues are key objects or elements in the image that are relevant to the user's query.
    """
    
    llm: OpenaiGPTLLM  # Language model used for generating visual cues

    def _run(self, qid: str, query: str, image_path: str):
        """
        Main execution method for visual cue generation.
        
        Args:
            qid (str): Query identifier
            query (str): User's text query about the image
            image_path (str): Path to the image file
            
        Returns:
            dict: Contains the filtered visual cues identified in the image
        """
        # Log the start of visual cue generation process
        self.callback.info(self.workflow_instance_id, progress='VisualCueGeneration', message=f'\nworkflow_instance_id: {self.workflow_instance_id}')
        
        # Load the image from the provided path
        img = read_image(input_source=image_path)
        if img is None:
            self.callback.error(self.workflow_instance_id, f"Failed to load image from {image_path}")
            return None
            
        # Store the image in the short-term memory for later use
        self.stm(self.workflow_instance_id)['image_cache'] = {'<image_0>': img}
        self.stm(self.workflow_instance_id)['prompt'] = query
        self.stm(self.workflow_instance_id)['id'] = qid
        self.stm(self.workflow_instance_id)['final_all_candidates'] = []
        self.stm(self.workflow_instance_id)['prompt_tokens'] = 0
        self.stm(self.workflow_instance_id)['completion_tokens'] = 0

        # Get the user's question from short-term memory
        question = self.stm(self.workflow_instance_id)['prompt']

        # Create a conversation prompt for visual cue generation
        conversation = get_visual_cues_generation_conversation(question)
   
        # Generate visual cues using the language model
        response = self.llm.generate(conversation)
        if not response or 'choices' not in response or not response['choices']:
            self.callback.error(self.workflow_instance_id, "Failed to get valid response from LLM")
            return None
            
        try:
            # Extract the content and token usage from the LLM response
            res = response['choices'][0]['message']['content']
            prompt_tokens = response['usage']['prompt_tokens']
            completion_tokens = response['usage']['completion_tokens']
        except KeyError as e:
            self.callback.error(self.workflow_instance_id, f"Missing key in LLM response: {e}")
            return None
        
        # Track token usage for monitoring purposes
        self.stm(self.workflow_instance_id)['prompt_tokens'] = prompt_tokens
        self.stm(self.workflow_instance_id)['completion_tokens'] = completion_tokens
        
        # Log the raw visual cues generated by the model
        self.callback.info(self.workflow_instance_id, progress='VisualCueGeneration', message=f'\nVisualCuesGeneration: {res}')
        
        # Extract target objects from the LLM response
        targets = extract_targets(res)
        targets = split_targets_sentence(targets)
        if targets is None:
            visual_cues = None
        else:
            # Filter out pronouns from visual cues
            visual_cues = [t for t in targets if not include_pronouns(t)]
            
        if visual_cues is None:
            visual_cues = []
        
        # Store the identified visual cues in short-term memory
        self.stm(self.workflow_instance_id)['visual_cue'] = visual_cues

        # Create an image tree for hierarchical image analysis
        image_tree = ImageTree(
            image_pil=img,
            patch_size=SMALLEST_SIZE
        )
        self.stm(self.workflow_instance_id)['tree'] = image_tree

        # Initialize variables for confidence-based filtering
        root_node = image_tree.root
        decomposed_question_template = DECOMPOSED_QUESTION_TEMPLATE
        answering_confidence_threshold_upper = ANSWERING_CONFIDENCE_THRESHOLD_UPPER
        filtered_visual_cues = []
        
        # If multiple visual cues are detected, filter them based on confidence
        if len(visual_cues) > 1:
            for target in visual_cues:
                # Special handling for 'all X' type cues
                if target.startswith("all "):
                    filtered_visual_cues.append(target)
                    continue
                    
                # Prepare inputs for confidence evaluation
                inputs = {
                    "node": root_node,
                    "image_pil": img,
                    "confidence_type": "answering",
                    "input_ele": decomposed_question_template.format(target)
                }
                
                # Generate a conversation to assess confidence in the visual cue
                conversation = get_confidence_conversation(**inputs)
                if not self.llm.logprobs:
                    self.llm.logprobs = True
                    self.llm.top_logprobs = 5
                    
                # Generate response with log probabilities for confidence calculation
                llm_response = self.llm.generate(conversation)
                
                # Update token usage statistics
                prompt_tokens = self.stm(self.workflow_instance_id)['prompt_tokens']
                completion_tokens = self.stm(self.workflow_instance_id)['completion_tokens']
                self.stm(self.workflow_instance_id)['prompt_tokens'] = prompt_tokens + llm_response['usage']['prompt_tokens']
                self.stm(self.workflow_instance_id)['completion_tokens'] = completion_tokens + llm_response['usage']['completion_tokens']
                
                # Calculate confidence score for this visual cue
                confidence = calculate_confidence_from_logprobs(llm_response)
                
                # Only keep visual cues with confidence below the threshold
                # (indicating they need further search/verification)
                if confidence < answering_confidence_threshold_upper:
                    filtered_visual_cues.append(target)
        else:
            # If only one visual cue, keep it without filtering
            filtered_visual_cues = visual_cues[:]
        
        # Store the final filtered visual cues in short-term memory
        if len(filtered_visual_cues) == 0:
            self.stm(self.workflow_instance_id)['visual_cues'] = None
        else:
            self.stm(self.workflow_instance_id)['visual_cues'] = filtered_visual_cues
                
        # Log the identified visual cues
        self.callback.info(self.workflow_instance_id, progress='VisualCueGeneration', message=f'\nVisualCues: {visual_cues}')
        
        # Return the filtered visual cues for the next stage in the workflow
        return {"visual_cues": filtered_visual_cues}