import pprint
import re  # noqa: F401

import six


class IntegrationApiUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'configuration': 'dict(str, object)',
        'description': 'str',
        'enabled': 'bool'
    }

    attribute_map = {
        'configuration': 'configuration',
        'description': 'description',
        'enabled': 'enabled'
    }

    def __init__(self, configuration=None, description=None, enabled=None):  # noqa: E501
        """IntegrationApiUpdate - a model defined in Swagger"""  # noqa: E501
        self._configuration = None
        self._description = None
        self._enabled = None
        self.discriminator = None
        if configuration is not None:
            self.configuration = configuration
        if description is not None:
            self.description = description
        if enabled is not None:
            self.enabled = enabled

    @property
    def configuration(self):
        """Gets the configuration of this IntegrationApiUpdate.  # noqa: E501


        :return: The configuration of this IntegrationApiUpdate.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._configuration

    @configuration.setter
    def configuration(self, configuration):
        """Sets the configuration of this IntegrationApiUpdate.


        :param configuration: The configuration of this IntegrationApiUpdate.  # noqa: E501
        :type: dict(str, object)
        """

        self._configuration = configuration

    @property
    def description(self):
        """Gets the description of this IntegrationApiUpdate.  # noqa: E501


        :return: The description of this IntegrationApiUpdate.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this IntegrationApiUpdate.


        :param description: The description of this IntegrationApiUpdate.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def enabled(self):
        """Gets the enabled of this IntegrationApiUpdate.  # noqa: E501


        :return: The enabled of this IntegrationApiUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this IntegrationApiUpdate.


        :param enabled: The enabled of this IntegrationApiUpdate.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IntegrationApiUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IntegrationApiUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
