import pprint
import re  # noqa: F401

import six


class TaskExecLog(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'log': 'str',
        'task_id': 'str',
        'created_time': 'int'
    }

    attribute_map = {
        'log': 'log',
        'task_id': 'taskId',
        'created_time': 'createdTime'
    }

    def __init__(self, log=None, task_id=None, created_time=None):  # noqa: E501
        """TaskExecLog - a model defined in Swagger"""  # noqa: E501
        self._log = None
        self._task_id = None
        self._created_time = None
        self.discriminator = None
        if log is not None:
            self.log = log
        if task_id is not None:
            self.task_id = task_id
        if created_time is not None:
            self.created_time = created_time

    @property
    def log(self):
        """Gets the log of this TaskExecLog.  # noqa: E501


        :return: The log of this TaskExecLog.  # noqa: E501
        :rtype: str
        """
        return self._log

    @log.setter
    def log(self, log):
        """Sets the log of this TaskExecLog.


        :param log: The log of this TaskExecLog.  # noqa: E501
        :type: str
        """

        self._log = log

    @property
    def task_id(self):
        """Gets the task_id of this TaskExecLog.  # noqa: E501


        :return: The task_id of this TaskExecLog.  # noqa: E501
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this TaskExecLog.


        :param task_id: The task_id of this TaskExecLog.  # noqa: E501
        :type: str
        """

        self._task_id = task_id

    @property
    def created_time(self):
        """Gets the created_time of this TaskExecLog.  # noqa: E501


        :return: The created_time of this TaskExecLog.  # noqa: E501
        :rtype: int
        """
        return self._created_time

    @created_time.setter
    def created_time(self, created_time):
        """Sets the created_time of this TaskExecLog.


        :param created_time: The created_time of this TaskExecLog.  # noqa: E501
        :type: int
        """

        self._created_time = created_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaskExecLog, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskExecLog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
