import pprint
import re  # noqa: F401

import six


class WorkflowTag(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rate_limit': 'RateLimit'
    }

    attribute_map = {
        'rate_limit': 'rateLimit'
    }

    def __init__(self, rate_limit=None):  # noqa: E501
        """WorkflowTag - a model defined in Swagger"""  # noqa: E501
        self._rate_limit = None
        self.discriminator = None
        if rate_limit is not None:
            self.rate_limit = rate_limit

    @property
    def rate_limit(self):
        """Gets the rate_limit of this WorkflowTag.  # noqa: E501


        :return: The rate_limit of this WorkflowTag.  # noqa: E501
        :rtype: RateLimit
        """
        return self._rate_limit

    @rate_limit.setter
    def rate_limit(self, rate_limit):
        """Sets the rate_limit of this WorkflowTag.


        :param rate_limit: The rate_limit of this WorkflowTag.  # noqa: E501
        :type: RateLimit
        """

        self._rate_limit = rate_limit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkflowTag, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkflowTag):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
