- name: TaskSplitter
  llm: ${sub|gpt}
  chunk_size: 8
  concurrency: 1
  special_task: sort
- name: TaskGenerater
  llm: ${sub|gpt}
  concurrency: 1
  num_branches_response: 1
  num_branches_response_for_aggregater: 1
  num_branches_response_for_refiner: 1
  parse_method: parse_refine_answer
- name: TaskScore
  llm: ${sub|gpt}
  concurrency: 1
  eval_method: num_errors
- name: KeepBestN
  llm: ${sub|gpt}
  best_n: 1
  higher_is_better: False
  concurrency: 1
- name: TaskConcluder
  llm: ${sub|gpt}
  concurrency: 1
- name: GoTTaskExitMonitor
