- name: Think
  llm: ${sub|text_res}
  output_parser:
    name: StrParser
  max_steps: 8
  example: |
        Question: Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?
        Thought 1: The question simplifies to "The Simpsons" character Milhouse is named after who. I only need to search Milhouse and find who it is named after.
        Action 1: Search[Milhouse]
        Observation 1: Milhouse Mussolini Van Houten is a recurring character in the Fox animated television series The Simpsons voiced by Pamela Hayden and created by Matt Groening.
        Thought 2: The paragraph does not tell who Milhouse is named after, maybe I can look up "named after".
        Action 2: Lookup[named after]
        Observation 2: (Result 1 / 1) Milhouse was named after U.S. president Richard Nixon, whose middle name was Milhous.
        Thought 3: Milhouse was named after U.S. president Richard Nixon, so the answer is Richard Nixon.
        Action 3: Finish[Richard Nixon]
  

- name: Action
  llm: ${sub|text_res}
  output_parser:
    name: StrParser

- name: WikiSearch

- name: ReactOutput
