- name: VisualCueGeneration
  llm: ${sub|gpt}

- name: ZoomEyePreprocess

- name: ZoomEyeSearch
  llm: ${sub|gpt}
  
- name: ZoomEyeSearchCheck

- name: ZoomEyeLoopCheck

- name: ZoomEyeOutput
  llm: ${sub|gpt}

